//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TreesTestTask.Migrations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlMigrations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlMigrations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TreesTestTask.Migrations.Resources.SqlMigrations", typeof(SqlMigrations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE FUNCTION get_nodes_hierarchy(RootName varchar(64))
        ///    RETURNS TABLE
        ///            (
        ///                &quot;Id&quot;       INT,
        ///                &quot;Name&quot;     varchar(64),
        ///                &quot;ParentId&quot; INT,
        ///                &quot;TreeId&quot;   INT
        ///            )
        ///    LANGUAGE plpgsql
        ///AS
        ///$$
        ///BEGIN
        ///    RETURN QUERY (WITH RECURSIVE Tree AS (SELECT *
        ///                                          FROM &quot;Nodes&quot; as node
        ///                                          WHERE node.&quot;Name&quot; = RootName
        ///                              [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetNodesHierarchyStoredProcedureCreatiion {
            get {
                return ResourceManager.GetString("GetNodesHierarchyStoredProcedureCreatiion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetNodesHierarchyStoredProcedureDeletion {
            get {
                return ResourceManager.GetString("GetNodesHierarchyStoredProcedureDeletion", resourceCulture);
            }
        }
    }
}
